# Recursive FFT

In [11]:
import numpy as np

In [12]:
def myFFT(f):
    N = len(f)
    
    if N==1:
        return f
    
    if N%2!=0:
        return []
        
    g = []
    h = []
    Wbar = np.exp(-2.j*np.pi/N)
    for n in range(N//2):
        g.append(   f[n] + f[n+N//2] )
        h.append( ( f[n] - f[n+N//2] )*Wbar**n )
    G = myFFT(g)
    H = myFFT(h)
    F = np.vstack((G,H)).T.flatten()
    return F

In [13]:
f = np.random.rand(16)

In [14]:
F = myFFT(f)

In [15]:
F

array([ 6.47171029+0.j        ,  1.33697542+1.10962068j,
       -0.12326805+0.07892296j, -0.37559818+1.5769578j ,
        0.03223915+0.97998578j, -0.46471034-0.30451539j,
       -0.84719699+0.28833527j, -0.49628994-0.30463533j,
        1.48248173+0.j        , -0.49628994+0.30463533j,
       -0.84719699-0.28833527j, -0.46471034+0.30451539j,
        0.03223915-0.97998578j, -0.37559818-1.5769578j ,
       -0.12326805-0.07892296j,  1.33697542-1.10962068j])

In [16]:
np.fft.fft(f)

array([ 6.47171029+0.j        ,  1.33697542+1.10962068j,
       -0.12326805+0.07892296j, -0.37559818+1.5769578j ,
        0.03223915+0.97998578j, -0.46471034-0.30451539j,
       -0.84719699+0.28833527j, -0.49628994-0.30463533j,
        1.48248173+0.j        , -0.49628994+0.30463533j,
       -0.84719699-0.28833527j, -0.46471034+0.30451539j,
        0.03223915-0.97998578j, -0.37559818-1.5769578j ,
       -0.12326805-0.07892296j,  1.33697542-1.10962068j])

In [17]:
myFFT([5,4,1,3])

array([13.+0.j,  4.-1.j, -1.+0.j,  4.+1.j])

In [18]:
np.fft.fft([5,4,1,3])

array([13.+0.j,  4.-1.j, -1.+0.j,  4.+1.j])